### ISSUE TITLE
403 even if whitelisted

### ISSUE THREAD

**Issue by sahara101** [hhftechnology/ipwhitelistshaper#2]
Hello, I have tried adding the plugin, but I get 403 even when whitelisted. 

DNS CF with proxy enabled.
Deployed on VPS with pangolin.
Using Middleware Manager - priority 110 for shaper and 120 for error-pages (also tried with same prio).

Navigating to https://files.mydomain.eu/  - error 403
Navigating to https://files.mydomain.eu/knock-knock 

Yu see already pending because I tested before and did not yet get a new code when I opened the issue.

```
Approval Required
An approval request is already pending. Please use the validation code below.

Validation code: strawberry

An administrator needs to approve your access using this code.
```

I get this notification

```
Access request from myip
Validation code: strawberry
Approve: https://approve.mydomain.eu/approve?ip=myCortectExternalIP&token=sometoken&validationCode=strawberry&expiration=60
✅ Whitelisted myip for 60 seconds
```

It is AUTO WHITELISTING it. Should not happen. 

```
ubuntu@docker-vps:/docker/pangolin$ cat traefik/plugins-storage/ipwhitelistshaper/state.json
{
  "whitelistedIPs": {
    "MyIP": {
      "expiresAt": "2025-05-11T07:45:06.508110887Z",
      "validationId": "730f06db7518d392533e3f8d9ec09c64",
      "validationCode": "strawberry"
    }
  },
  "pendingApprovals": {},
  "lastRequestedIP": {
    "MyIP": "2025-05-11T07:43:50Z"
  }
}
```

Navigating to https://files.mydomain.eu/  again - error 403

What happens when the notification appears is random. It will either:

Send it and directly approve it. Opening the link says already approved. The IP is NOT added to whitelist.
Send it and directly approve it. Opening the link says already approved. The IP is NOT added to whitelist. Wait some time and open the link again with same word; it say successfully approved for 60s and add it to whitelist.
Send it and not approve it - I need to click on the link - IP added to whitelist.

My conf: 

Middleware Manager - added to templates.

```
    - id: "ipwhitelistshaper"
      name: "IP Whitelist Shaper"
      type: "plugin"
      config:
        ipwhitelistshaper:
          knockEndpoint: "/knock-knock"
          approvalURL: "https://approve.mydomain.eu"
          notificationURL: "https://discord.com/api/webhooks/myhook"
          defaultPrivateClassSources: true
          expirationTime: 300
          ipStrategyDepth: 1
          secretKey: ""
          excludedIPs: []
          whitelistedIPs:
            - "127.0.0.1/32"
            - "192.168.1.0/24"
            - "10.0.0.0/8"
          storageEnabled: true
          storagePath: "/plugins-storage/ipwhitelistshaper"
          saveInterval: 30
```

Docker compose

`  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped

    network_mode: service:gerbil # Ports appear on the gerbil service

    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    env_file:
      - .env
    volumes:
      - ./config/traefik:/etc/traefik:ro # Volume to store the Traefik configuration
      - ./config/letsencrypt:/letsencrypt # Volume to store the Let's Encrypt certificates
      - ./config/traefik/logs:/var/log/traefik # Volume to store Traefik logs
      - ./config/traefik/rules:/rules
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/plugins-storage:/plugins-storage:rw  <-- added for shaper
      - ./traefik/plugins-storage:/plugins-local:rw` <-- added for shaper (but not used because I use the catalog)

Static config

```
experimental:
  plugins:
    others...
    ipwhitelistshaper:
      moduleName: github.com/hhftechnology/ipwhitelistshaper
      version: v1.0.6
```

Dynamic config 

```
    router-for-ipwhitelist-approval:
      rule: "Host(`approve.mydomain.eu`)"
      entryPoints:
        - websecure
      middlewares:
        - ipwhitelistshaper@file
      service: noop@internal
      priority: 110
      tls:
        certResolver: letsencrypt
```

resvurce-ovverides

```
    routers:
        1-router-auth:
            entryPoints:
                - websecure
            middlewares:
                - error-pages@file
                - ipwhitelistshaper@file
                - buffering@file
                - headers-standard@file
                - badger@http
            priority: 100
            rule: "Host(`files.mydomin.eu`)"
            service: 1-service@http
            tls:
                certResolver: letsencrypt
```

Thanks!

**Comment by hhftechnology** [comment]
you have to put separate routers in your dynamic config did you put them ?

```yaml
    # Add this new router for the knock-knock endpoint
    knock-knock-router:
      entryPoints:
        - websecure
      middlewares:
        - ipwhitelistshaper@file
      priority: 110  # Higher priority to take precedence
      rule: "Host(`wallos.development.hhf.technology`) && Path(`/knock-knock`)"
      service: 2-service@http
      tls:
        certResolver: letsencrypt
        
    # Add this new router for the approval endpoint
    approve-router:
      entryPoints:
        - websecure
      middlewares:
        - ipwhitelistshaper@file
      priority: 110  # Higher priority to take precedence
      rule: "Host(`wallos.development.hhf.technology`) && PathPrefix(`/approve/`)"
      service: 2-service@http
      tls:
        certResolver: letsencrypt
```

these are separate than your main resource router
